<html lang='en'>

<body>
    <div style='margin-top: 20px; margin-right: 100px; margin-bottom: 20px; margin-left: 100px; border: 2px solid black;'>
        <div style='text-align:center'>
            <h3>
                <p>SHRI G. S. INSTITUTE OF TECHNOLOGY & SCIENCE, INDORE</p>
                <p></p>
            </h3>
            <h5><U>CWN MAINTENANCE</U></h5>
        </div>
        <div>
            <p style='text-align:right; font-size:10.0pt;font-family:Arial;'>
                <span>Date:</span>$data.empNumber$ &nbsp;
                <span>Time:</span>$data.empNumber$
            </p>
            <p style='text-align:left; font-size:10.0pt;font-family:Arial;'><span>Name of
                    Department:</span>$data.empNumber$</p>
        </div>
        <hr>
        <div>
            <table style='border-collapse: collapse; border: 1px solid black; table-layout: auto; margin-right: 50px; margin-left: 50px; width: 100%; font-size:10.0pt;font-family:Arial;'>
                <thead>
                    <tr style='border: 1px solid black;'>
                        <th style='border: 1px solid black;' scope='col'>S.no.</th>
                        <th style='border: 1px solid black;' scope='col'>Details of Problem/Complaint</th>
                        <th style='border: 1px solid black;' scope='col'>Clear location of Problem/Complaint</th>
                    </tr>
                </thead>
                <tbody>
                    <tr style='border: 1px solid black;'>
                        <td style='border: 1px solid black;'>&nbsp;</td>
                        <td style='border: 1px solid black;'>&nbsp;</td>
                        <td style='border: 1px solid black;'>&nbsp;</td>
                    </tr>
                    <tr style='border: 1px solid black;'>
                        <td style='border: 1px solid black;'>&nbsp;</td>
                        <td style='border: 1px solid black;'>&nbsp;</td>
                        <td style='border: 1px solid black;'>&nbsp;</td>
                    </tr>
                </tbody>
                <tfoot>
                    <tr style='border: 1px solid black;'>
                        <td style='border: 1px solid black;' colspan='2'>Signature of HOD</td>
                        <td style='border: 1px solid black;'>Signature of Member</td>
                    </tr>
                </tfoot>

            </table>
            </div>
<hr>
        <div>
                <p style='text-align: left;font-size:10.0pt;font-family:Arial;'>For CWN use: &nbsp;</p>
                <br>
                <p style='text-align: left;font-size:10.0pt;font-family:Arial;'>Problem Identified: &nbsp;<span>$data.empNumber$</span></p>
                <p style='text-align: left;font-size:10.0pt;font-family:Arial;'>Material required (if any): &nbsp;<span>$data.empNumber$</span></p>
                <br>
                <p style='text-align: left;font-size:10.0pt;font-family:Arial;'>Signature of network engineer: &nbsp;</p>
                <p style='text-align: left;font-size:10.0pt;font-family:Arial;'>Report of CNW I/C (if any): &nbsp;<span>$data.empNumber$</span></p>
        		<br>
        </div>
        <hr style='border-top: dotted 1px;' />
        <div>
            <h4 style='text-align:center;'>STATUS OF REPORTED PROBLEM</h4>
            <p style='text-align: left;font-size:10.0pt;font-family:Arial;'>
                <span>Above complaint is resolved on Date:</span>$data.empNumber$ &nbsp;
                <span>Time:</span>$data.empNumber$ &nbsp;
            </p>
            <p style='text-align: left;font-size:10.0pt;font-family:Arial;'>Remaks(if any) &nbsp;<span>$data.empNumber$</span></p>
            <br>
            <h5 style='text-align: right'>
                <P>Signature & Seal of Dept.</P>
            </h5>

        </div>
    </div>
</body>

</html>