<html lang='en'>

<body>
    <div style='margin-top: 20px; margin-right: 100px; margin-bottom: 20px; margin-left: 100px; border: 2px solid black;'>
        <div style='text-align:center'>
            <h3>
                <p>SHRI G. S. INSTITUTE OF TECHNOLOGY & SCIENCE, INDORE</p>
            </h3>
            <h5><U>ENGINEERING CELL / CENTRAL WORKSHOP</U></h5>
        </div>
        <div>
        <h5>(A)<u>Indent for Civil Maintenance and Central Workshop Related Works</u></h5>
            <p style='font-size:10.0pt;font-family:Arial;'>
                <span style='text-align:left;'>No.:</span>$data.empNumber$ &nbsp;
                <span style='text-align:right;'>Date:</span>$data.empNumber$
            </p>
            <p style='text-align:left; font-size:10.0pt;font-family:Arial;'>Name of
                    Department:<u>Department of Computer Engineering</u></p>
        </div>
        <hr>
        <div>
            <table style='border-collapse: collapse; border: 1px solid black; table-layout: auto; margin-right: 50px; margin-left: 50px; width: 100%; font-size:10.0pt;font-family:Arial;'>
                <thead>
                    <tr style='border: 1px solid black;'>
                        <th style='border: 1px solid black;' scope='col'>S.no.</th>
                        <th style='border: 1px solid black;' scope='col'>Details of the work</th>
                        <th style='border: 1px solid black;' scope='col'>Clear location of work</th>
                    </tr>
                </thead>
                <tbody>
                    <tr style='border: 1px solid black;'>
                        <td style='border: 1px solid black;'>&nbsp;</td>
                        <td style='border: 1px solid black;'>&nbsp;</td>
                        <td style='border: 1px solid black;'>&nbsp;</td>
                    </tr>
                    <tr style='border: 1px solid black;'>
                        <td style='border: 1px solid black;'>&nbsp;</td>
                        <td style='border: 1px solid black;'>&nbsp;</td>
                        <td style='border: 1px solid black;'>&nbsp;</td>
                    </tr>
                </tbody>
               
            </table>
            <br>
            <table style='border-collapse: collapse; border: 1px solid black; table-layout: auto; margin-right: 50px; margin-left: 50px; width: 100%; font-size:10.0pt;font-family:Arial;'>
            <tr style='border: 1px solid black;'>
                        <th style='border: 1px solid black;' colspan='2'>Signature of HOD</th>
                        <th style='border: 1px solid black;'>Signature of Member</th>
                    </tr>
                    <tr >
                        <td >&nbsp;</td>
                        <td >&nbsp;</td>
                    </tr>
                    <tr >
                        <td >&nbsp;</td>
                        <td >&nbsp;</td>
                    </tr>
                    </table>
        </div>
              <div>
            <h5>(B)<u>For:Use of Engineering Cell</u></h5>
             <table style='border-collapse: collapse; border: 1px solid black; table-layout: auto; margin-right: 50px; margin-left: 50px; width: 100%; font-size:10.0pt;font-family:Arial;'>
                
                    <tr style='border: 1px solid black;'>
                        <th style='border: 1px solid black;' scope='col'>1</th>
                        <th style='border: 1px solid black;' scope='col'>Serial no. of complaint register and date</th>
                        <td style='border: 1px solid black;'>
                        <p style='font-size:10.0pt;font-family:Arial;'>
                <span style='text-align:left;'>Complaint No.:</span>$data.empNumber$ &nbsp;
                <span style='text-align:right;'>Date:</span>$data.empNumber$
            </p>
                        </td>
                    </tr>
              <tr style='border: 1px solid black;'>
                        <th style='border: 1px solid black;' scope='col'>2</th>
                        <th style='border: 1px solid black;' scope='col'>Name of worker whom work is alloted</th>
                        <td style='border: 1px solid black;'></td>
                    </tr>
                    <tr style='border: 1px solid black;'>
                        <th style='border: 1px solid black;' scope='col'>3</th>
                        <th style='border: 1px solid black;' scope='col'>Name of supervisor</th>
                        <td style='border: 1px solid black;'></td>
                    </tr>
                    <tr style='border: 1px solid black;'>
                        <th style='border: 1px solid black;' scope='col'>4</th>
                        <th style='border: 1px solid black;' scope='col'>Material Required</th>
                        <td style='border: 1px solid black;'></td>
                    </tr>
                    <tr style='border: 1px solid black;'>
                        <th style='border: 1px solid black;' scope='col'>5</th>
                        <th style='border: 1px solid black;' scope='col'>Date of completion of work</th>
                        <td style='border: 1px solid black;'>Date:$data.empNumber$</td>
                    </tr>
                    <tr style='border: 1px solid black;'>
                        <th style='border: 1px solid black;' scope='col'>6</th>
                        <th style='border: 1px solid black;' scope='col'>Supervisor's report</th>
                        <td style='border: 1px solid black;'></td>
                    </tr>
                
               
            </table>
        </div>
        <div style='page-break-before: always;'>
           <h5><u>For:Electrical M&R Section</u></h5>
             <table style='border-collapse: collapse; border: 1px solid black; table-layout: auto; margin-right: 50px; margin-left: 50px; width: 100%; font-size:10.0pt;font-family:Arial;'>
                
                    <tr style='border: 1px solid black;'>
                        <th style='border: 1px solid black;' scope='col'>1</th>
                        <th style='border: 1px solid black;' scope='col'>Serial no. of complaint register and date</th>
                        <td style='border: 1px solid black;'>
                        <p style='font-size:10.0pt;font-family:Arial;'>
                <span style='text-align:left;'>Complaint No.:</span>$data.empNumber$ &nbsp;
                <span style='text-align:right;'>Date:</span>$data.empNumber$
            </p>
                        </td>
                    </tr>
              <tr style='border: 1px solid black;'>
                        <th style='border: 1px solid black;' scope='col'>2</th>
                        <th style='border: 1px solid black;' scope='col'>Name of worker whom work is alloted</th>
                        <td style='border: 1px solid black;'></td>
                    </tr>
                    <tr style='border: 1px solid black;'>
                        <th style='border: 1px solid black;' scope='col'>3</th>
                        <th style='border: 1px solid black;' scope='col'>Name of supervisor</th>
                        <td style='border: 1px solid black;'></td>
                    </tr>
                    <tr style='border: 1px solid black;'>
                        <th style='border: 1px solid black;' scope='col'>4</th>
                        <th style='border: 1px solid black;' scope='col'>Material Required</th>
                        <td style='border: 1px solid black;'></td>
                    </tr>
                    <tr style='border: 1px solid black;'>
                        <th style='border: 1px solid black;' scope='col'>5</th>
                        <th style='border: 1px solid black;' scope='col'>Date of completion of work</th>
                        <td style='border: 1px solid black;'>Date:$data.empNumber$</td>
                    </tr>
                    <tr style='border: 1px solid black;'>
                        <th style='border: 1px solid black;' scope='col'>6</th>
                        <th style='border: 1px solid black;' scope='col'>Supervisor's report</th>
                        <td style='border: 1px solid black;'></td>
                    </tr>
                
               
            </table>

        </div>
    </div>
</body>

</html>