<html lang='en'>

<body>
    <div style='margin-top: 20px; margin-right: 100px; margin-bottom: 20px; margin-left: 100px; border: 2px solid black;'>
        <div style='text-align:center'>
            <h3>
                <p>SHRI G. S. INSTITUTE OF TECHNOLOGY & SCIENCE, INDORE</p>
            
            </h3>
            <h5><U>Telephone Complain Form</U></h5>
        </div>
        <div>
            <p style='text-align:right; font-size:10.0pt;font-family:Arial;'>
                <span>Date:</span>$data.empNumber$ &nbsp;
          
            </p>
            
        </div>
        <hr>
        <div>
            <table style='border-collapse: collapse; border: 1px solid black; table-layout: auto; margin-right: 50px; margin-left: 50px; width: 100%; font-size:10.0pt;font-family:Arial;'>
                <thead>
                    <tr style='border: 1px solid black;'>
                        <th style='border: 1px solid black;' scope='col'>S.no.</th>
                        <th style='border: 1px solid black;' scope='col'>Extension no.</th>
                        <th style='border: 1px solid black;' scope='col'>Location(Department/Section)</th>
                        <th style='border: 1px solid black;' scope='col'>Problem/Complain Description</th>
                        <th style='border: 1px solid black;' scope='col'>Date at which complain submitted</th>
                        <th style='border: 1px solid black;' scope='col'>Date at which complain resolved</th>
                    </tr>
                </thead>
                <tbody>
                    <tr style='border: 1px solid black;'>
                        <td style='border: 1px solid black;'>&nbsp;</td>
                        <td style='border: 1px solid black;'>&nbsp;</td>
                        <td style='border: 1px solid black;'>&nbsp;</td>
                    </tr>
                    <tr style='border: 1px solid black;'>
                        <td style='border: 1px solid black;'>&nbsp;</td>
                        <td style='border: 1px solid black;'>&nbsp;</td>
                        <td style='border: 1px solid black;'>&nbsp;</td>
                    </tr>
                </tbody>
           

            </table>
             <h5 style='text-align: right'>
                <P>Head</P>
                <p> Department of computer engineering</p>
            </h5>
        </div>
        
        <hr style='border-top: dotted 1px;' />
        <div>
            <h4 style='text-align:center;'>Receipt</h4>
            <p style='text-align: left;font-size:10.0pt;font-family:Arial;'>The Complainnt related to Extension No.
                <span>$data.empNumber$ &nbsp;</span> Is resolved on
                <span>$data.empNumber$ &nbsp;</span>
            </p>
        
        </div>
    </div>
</body>

</html>